ai-dynamo/nixl

- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/infra/mem_section.h
- src/infra/nixl_memory_section.cpp
* Using backend pointer in the section key, look ups are easier and in future multiple backends of the same type can be handled eaiser.
* With the previous changes and some method arguments changes in the memory section classes, now only the deserializer for remote section memory requires a map from backend type to backend engine, which is passed by reference in agent which holds such a map.
> Mem section: Minor restructuring to move the backend decision making fully to the agent

- src/utils/ucx/ucx_utils.cpp
* Issue: UCP falls back to send-recv instead of RDMA READ
* Fix: Temporarily disable UCP_ERR_HANDLING_MODE_PEER during ep create
> ucx_utils: Fix performance issue with ucp_get_nbx path

- src/api/python/_api.py
Fix spell error in python _api.py print while
initializing.
> python API: Spell error in python _api.py

- src/core/meson.build
- src/plugins/meson.build
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/meson.build
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- src/plugins/ucx_mo/ucx_mo_plugin.cpp
- test/unit/plugins/meson.build
- test/unit/plugins/ucx/ucx_backend_test.cpp
- test/unit/plugins/ucx_mo/meson.build
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
Replaces PR #30 (see unit test outputs there)
Adds new UCX-based backend that allows associating NIXL
logical "devices" with different UCX workers.
The primary motivation is that UCX v1.18 doesn't
support more than one GPGPU per UCX context.
NOTE: this is expected to be fixed in UCX v1.19
so this backend might be viewed as a workaround
unless other uses will be found.
Limitations:
* Doesn't support loopback transfers
* Doesn't support VRAM
Both limitations will be removed in a follow-up PRs
> Multi-Object (MO) UCX backend implementation (rebased over code restructuring PR)

- test/unit/plugins/ucx/ucx_backend_test.cpp
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
To More thoroughly test block-to-device distribution Make Source and destination block-to-device distribution uneven:
* For source blocks use round-robin
* For destination - block-wise
> ucx_mo_backend_test: add distribution function

- src/plugins/ucx_mo/ucx_mo_backend.cpp
- test/unit/plugins/ucx/meson.build
- test/unit/plugins/ucx/ucx_backend_test.cpp
- test/unit/plugins/ucx_mo/meson.build
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
* Fix meson build scripts to build with CUDA support when detected
* Fix the cuda include files
* Enable "VRAM_SEG" in UCX_MO backend
* Replace "USE_VRAM" with "HAVE_CUDA" in UCX and UCX_MO tests
> ucx/ucx_mo tests: fix for CUDA buffer case

- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/infra/nixl_memory_section.cpp
- test/nixl/agent_example.cpp
* There was an ordering bug in agent destructor when some memories were left registered. Also how local section destructor worked had a bug. Both fixed.
> Agent: Fixed a bug in auto deregistration

- src/api/python/_api.py
* set memory type "cuda" if tensor device starts with "cuda" instead of setting directly
* add UCX backend as a parameter for genNotif call in send_notif
> python API: Fix tensor device type check and send_notif

- src/core/nixl_agent.cpp
- test/python/nixl_api_test.py
Add a fix in the agent code to properly release previously allocated backend request handles when reposting a handle.
Updates our python API test to check for this case.
> agent: properly release backend handles for reposts

- src/core/nixl_agent.cpp
When merging descriptors in makeXfer, only use a pointer to look ahead to reduce the number of descriptor copies.
> agent: small optimization to reduce desc copying

- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- test/python/nixl_api_test.py
- test/python/nixl_bindings_test.py
This PR does two thing: 
- adds explicit typing for python API parameters (where appropriate).
- remove workarounds to enable fully automatic backend selection for python users. This includes updating the bindings API to make backend passing optional.
Testing of automatic backend selection has already been done in C++, and is implicity tested in our python tests already. We will add some testing to python as well once we have a testing framework. 
The explicity typing here will make it a little easier to add Doxygen for the Python API (soon).
> python api: add typing and backend selection

- src/api/cpp/nixl.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/nixl_agent.cpp
* For both cpp and python. Clarified the comments accordingly too.
* A minor code clarity improvement in prepXferDlist cpp implementation
> Agent/API: renamed remote_agent to agent_name for prepXferDlist to be more clear.

- pyproject.toml
- src/api/python/__init__.py
- src/core/nixl_plugin_manager.cpp
- test/python/nixl_api_test.py
Update our wheel configuration and plugin manager to allow for plugins to be dynamically linked instead of needing static linking. This is done by updating our init python script.
> wheel: initial effort to allow dynamic linking of plugins

- meson.build
Lets switch to C++17 standard to build. We could use newer features and gtest will rely only on C++17 for later releases.
Tested-by: Subhadeep Bhattacharya <subhadeepb@nvidia.com>
Signed-off-by: Adit Ranadive <aranadive@nvidia.com>
> meson: Switch to C++17

- CODEOWNERS
- CODE_OF_CONDUCT.md
As Nixl is an open source project that wants to maximize community engagement in a safe and responsible manner this presents a code of conduct for both contributors and the ai-dynamo organization so there are clear policies for standards of behavior and appropriate responses.
Code of Conduct largely taken [here](from https://github.com/NVIDIA/TensorRT-LLM/blob/main/CODE_OF_CONDUCT.md)
> feat: Add code of conduct for project

- README.md
- contrib/Dockerfile
- contrib/build-container.sh
- contrib/build-wheel.sh
Dockerfile:
- Remove the MPI install for nixl library
- Update the nixl repo to use github version or local copy based on new build script arg
- Added support to have a uv wheel built within the container
Scripts:
- Added scripts for build container, uv wheel
- Build script for container can use Ubuntu 22.04 images if required
> contrib: Update dockerfiles and add scripts

- examples/python/blocking_send_recv_example.py
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- test/python/nixl_api_test.py
- test/python/nixl_bindings_test.py
Update our python API to always return bytes for notifications, as well as updating tests to account for this.
> python API: return bytes for python notifications

- src/infra/nixl_memory_section.cpp
- test/nixl/nixl_test.cpp
- util/test_cpp.sh
- util/test_python.sh
The use of the delimiter ';' to separate metadata and desc info during OOB transfer sometimes fails because this delimiter is present in the serialized metadata/desc string.
* Use custom delimiter string ";descriptor=" instead of ';'
* Add support for CPP and Python test in CI
> CPP test: Modified delimiter handling for OOB transfer

- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
Move descriptor list comm matrix preparation to prepXfer. This would allow applications that leverage single prepare followed by multiple post operations optimization
to avoid extra memory allocations and computations.
> backend/ucx_mo: Leverage prepXfer for preparing the transfer

- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
Add the option to select specific backends for send_notif, or allow automatic backend selection.
> python API: optional backends for send_notif

- README.md
I don't know why but this tarball does not have an autogen.sh (the one in the README):
https://github.com/openucx/ucx/releases/download/v1.18.0/ucx-1.18.0.tar.gz
but this one does (the one in CI where the config was copied from):
https://github.com/openucx/ucx/tarball/v1.18.0
> README: remove autogen.sh

- src/core/nixl_agent.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
* minor bug fix in best effort, if supportsLocal is not available.
* MO-UCX does not supportLocal fully yet, but the flag is set otherwise.
> Agent/MO-UCX: registerMem best effort fix, MO-UCX local transfer flag fix

- .gitlab/test_cpp.sh
- examples/cpp/meson.build
- examples/meson.build
- meson.build
This example wasn't part of meson, but it does work still.
> meson: add nixl_example to meson system

- examples/python/nixl_gds_example.py
- pyproject.toml
- src/api/python/_api.py
This PR removes disable_gds_backend from the pyproject.toml, and adds a python test that successfully runs on GDS on adv-dev-426
> python: initial gds test

- examples/python/nixl_gds_example.py
- pyproject.toml
- src/api/python/_api.py
- src/plugins/cuda_gds/gds_backend.cpp
- src/plugins/cuda_gds/gds_backend.h
- src/plugins/cuda_gds/gds_plugin.cpp
- src/plugins/cuda_gds/gds_utils.cpp
- src/plugins/cuda_gds/gds_utils.h
- src/plugins/cuda_gds/meson.build
- test/unit/plugins/cuda_gds/nixl_gds_test.cpp
This patch improves the plugin implementation with the following
1. Create a batch pool for GDS batches
2. Provide a way to split and create requests to work-around 16M shadow buffer limit in GDS
3. Use PrepXfer to pre-create the batches and keep it ready for submission
4. postXfer just does submission
5. All parameters are configurable through backend params
6. Improved C++ test to exercise and test all these options.
7. New Python test to ensure compatibility with Python API
> GDS: prepXfer usage, better test example

- .github/copy-pr-bot.yaml
- .github/workflows/build_validation.yml
- .github/workflows/external_contributor.yaml
NIXL's CI is currently inside the NVIDIA network and security protections require external contributions to be reviewed before they run on the internal network. Using `copy-pr-bot` we are able to meet those security requirements.
The bot examines the commits on the PR since branching from main checking for both commit author's membership in the ai-dynamo organization and for a signature that is verifiable (through it's registration on GitHub). In the event that both of those requirements are filled, you are on the happy path and no additional work is required.
If either of those verifications fails, GitLab CI will not run for that commit and will need to manually be triggered by a member of the ai-dynamo organization by adding a the comment `/ok to test`.
Here are some instructions for …
> ci: Enable external contributor flow for NIXL repo

- .gitlab/build.sh
- Doxyfile
- README.md
- meson.build
- meson_options.txt
- Add build_docs option to meson_options.txt
- Add Doxygen documentation build configuration in meson.build
- Update README.md with build options and documentation instructions
- Add documentation build location information
> CI: Add Doxygen documentation build support

- src/api/cpp/nixl_descriptors.h
- src/bindings/python/nixl_bindings.cpp
- src/infra/nixl_descriptors.cpp
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- test/nixl/desc_example.cpp
* In serialized form of nixlBasicDesc, it was using 24 bytes anyways on 64-bit systems, so no memory savings, while going to u64 can be useful for some backends.
* Also used constexpr as we moved to c++17, and now empty copyMeta can be removed from nixlBasicDesc.
> Descriptors: changed devID from 32-bits to 64-bits

- src/api/cpp/backend/backend_aux.h
- src/api/cpp/nixl.h
- src/api/cpp/nixl_descriptors.h
- src/infra/nixl_descriptors.cpp
- src/infra/nixl_memory_section.cpp
- test/nixl/desc_example.cpp
* Moved populate from descriptors to mem section.
* The enabled removal of copyMeta methods. They were only used in that method.
* Commented out some extra checks that should be done only in debug mode when added.
* Added few comments to nixl.h to clarify how sorted can be used, now that the populate method is removed.
> Descriptors: code reorg and clean up

- src/plugins/ucx/ucx_backend.cpp
Caught it by chance with address sanitizer (meson flag: -Db_sanitize=address,undefined)
> UCX: Fix memory leak in nixlUcxEngine

- src/api/cpp/nixl.h
- src/api/cpp/nixl_types.h
- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/infra/mem_section.h
- src/infra/nixl_descriptors.cpp
- src/infra/nixl_memory_section.cpp
- test/nixl/agent_example.cpp
* This allows one agent to notify remote agents about new memory regions
* This allows guardrails between agents so that each remote agent can transfer only to a subset of regions.
* Introducing new internal nixlSectionDesc which is used to cache the remote metadata blob to make sure an existing remote descriptor did not change its metadata during a new loadRemoteMD.
> Agent API: New method to get partial MD and allow partial MD loads

- src/plugins/cuda_gds/gds_backend.cpp
- test/unit/plugins/cuda_gds/nixl_gds_test.cpp
- File descriptor handles to be removed during de-register
- Update the test help information with appropriate limits.
> cuda_gds: Remove cached file handle during deregister

- src/api/cpp/nixl_params.h
- src/api/cpp/nixl_types.h
- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/core/nixl_plugin_manager.cpp
- src/core/plugin_manager.h
- src/core/sync.h
- src/utils/common/util.h
- test/gtest/meson.build
- test/gtest/mocks/mock_dram_engine.cpp
- test/gtest/mocks/mock_dram_engine.h
- test/gtest/multi_threading.cpp
- test/gtest/plugin_manager.cpp
- test/nixl/test_plugin.cpp
Current NIXL implementation sidesteps any considerations of executing in multi-threaded environment by leaving it up to the user to ensure that access to nixlAgent instance is synchronized. Extend this by adding a strict synchronization mode while also preserving existing mode but making it explicit.
To continue using NIXL with exactly the same performance set configuration variable disable_mt=true which statically removes all locking at build time.
When NIXL is compiled with multi-threading enabled still allow dynamic configurations via nixlAgentConfig->syncMode field:
- When set to NIXL_SYNC_NONE no locking is performed and behavior is similar as before this change with the small difference that dynamic check is performed every time the lock would be taken with strict model.
- When set …
> Implement multi-threading support

- meson.build
- meson_options.txt
- src/utils/common/nixl_log.cpp
Currently, `INFO` is used by default for release builds and `TRACE` for debug builds. Both `INFO` and `TRACE` should be available as the maximum log levels for release and debug builds respectively, but the default level should be set to `WARN`.
> Debug Infra: Fix NIXL log level

- .gitlab/test_python.sh
- examples/python/blocking_send_recv_example.py
- examples/python/partial_md_example.py
- src/api/cpp/nixl.h
- src/api/cpp/nixl_params.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/meson.build
- src/core/nixl_agent.cpp
- src/core/nixl_listener.cpp
- add method to check if a remote agent's metadata is available
- Rearrange metadata methods for consistency
> API: checkRemoteMD call

- meson.build
- src/utils/common/nixl_log.h
Simplify build scripts. absl::log provides DVLOG macro that is stripped in compile time with NDEBUG. So just need to define NDEBUG for release builds.
We want to keep most of the logs in release build, and remove only the ones in data path - NIXL_TRACE.
> UTILS/BUILD: Logging infra cleanups

- src/core/meson.build
On some systems (such as RedHat 8.6) it's needed to fix compilation.
> BUILD: Add stdc++fs link flag to for std::filesystem

- .gitlab/build.sh
- README.md
- contrib/Dockerfile
- src/core/nixl_plugin_manager.cpp
- src/plugins/meson.build
- src/plugins/posix/README.md
- src/plugins/posix/meson.build
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_backend.h
- src/plugins/posix/posix_plugin.cpp
- src/utils/common/status.h
- test/nixl/meson.build
- test/nixl/test_plugin.cpp
- test/unit/plugins/meson.build
- test/unit/plugins/posix/meson.build
- test/unit/plugins/posix/nixl_posix_test.cpp
Added a plugin to support POSIX type files.
> NIXL POSIX plugin

- README.md
- src/plugins/meson.build
I should have caught this the first time, we don't have to make liburing a requirement, some users might not have sudo privilege to install it.
> meson: don't require liburing

- .gitlab/test_cpp.sh
- contrib/Dockerfile
- src/plugins/posix/README.md
Disabling this test until we can figure out io_uring and Docker compatibility, and also fixing the Dockerfile
> CI: disable POSIX CI test

- src/api/cpp/nixl_descriptors.h
- src/api/cpp/nixl_types.h
- src/core/agent_data.h
- src/infra/mem_section.h
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- src/utils/common/nixl_time.h
- src/utils/ucx/ucx_utils.h
Apply `Prefer "using" over "typedef"` guidelines in src/ This commit doesn't change functionality, it is strictly visual.
Copy of https://github.com/ai-dynamo/nixl/pull/208
> refactor: Prefer "using" over "typedef" guideline implementation

- benchmark/nixlbench/src/main.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
- benchmark/nixlbench/src/worker/worker.cpp
- benchmark/nixlbench/src/worker/worker.h
Clean-up any ETCD state in case of interruption, we can only proceed once/while all ranks are present.
Issue observed with one instance being restarted:
```
$ nixlbench
Connecting to ETCD at http://localhost:2379
ETCD Runtime: Registered as rank 10 item 11 of 2
Init nixl worker, dev all rank 10, type target, hostname rock
Waiting for all processes to start... (expecting 2 total: 1 initiators and 1 targets)
```
> NIXLBench: Add ctrl-c handling for etcd cleanup

- benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
Proposal to use etcd `client->ls()` for barrier implementation and try to reduce sleep. Also currently we perform put()/get() which are not atomic as per my understanding.
> NIXLBench: Use directory listing and generation for barrier

- benchmark/nixlbench/src/main.cpp
- benchmark/nixlbench/src/worker/worker.cpp
- benchmark/nixlbench/src/worker/worker.h
Persist the environment until all ranks are done using it. For instance, the target can be waiting for etcd to get() the `/ack`, under `xferBenchEtcdRT::sendChar` from `xferBenchNixlWorker::exchangeIOV`, posted by the initiator (rank 0) which raced to exit and already destroyed it.
> NIXLBench: Persist environment until all ranks complete

- src/api/cpp/nixl.h
- src/core/agent_data.h
- src/core/nixl_agent.cpp
Use move semantics for nixlAgentData
> AGENT: Use std::unique_ptr for agent data

- test/nixl/nixl_test.cpp
First commit performs clean-ups and preparatory refactorings, second one implements multi-threading execution.
> Extend nixl_test with multi-threading

- .gitlab/test_cpp.sh
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_backend.h
Some nodes might not support io_uring. Add more related details to CI and code.
> POSIX: Add more logs

- .github/workflows/build_validation.yml
Replace the default `self-hosted` label with a custom `gitlab` label in the NVIDIA NIXL Validation workflow.
The `self-hosted` label is automatically assigned to all self-hosted GitHub runners and can't be removed.
We've added a new runner on Blossom infrastructure with a different toolchain.
To avoid workflow conflicts, we need to distinguish Gitlab and Blossom runners using separate labels.
> CI: Change default runner labels for NIXL validation workflow

- benchmark/nixlbench/meson.build
- benchmark/nixlbench/src/main.cpp
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
- benchmark/nixlbench/src/worker/worker.cpp
- benchmark/nixlbench/src/worker/worker.h
* Enable READ support for NVSHMEM
* Introduce synchronization to properly calculate time
* Introduce sync after (i)exchangeIOV and (ii)Warmup is complete
* Bug fix during printStats and createTransferDescLists
* Pass isTarget in printStats to restrict target processes from reducing result across procs (Temp fix)
* Fix createTransferDescLists to provide address within range with RR pattern
* Add cpprest lib during nvcc compilation for NVSHMEM
> NIXLBench: Bug fixes to properly create desclist and calculate stat + read support for nvshmem worker

- examples/python/blocking_send_recv_example.py
Fix: #260
Use `torch.set_default_device("cuda:0")` to select the device and simplify the code for the `--use-cuda` parameter , which was introduced in #221.
> python: use torch.set_default_device in blocking_send_recv_example.py

- src/plugins/ucx/ucx_backend.cpp
- src/utils/serdes/serdes.cpp
In UCX plugin, requests are always kept constructed. When marked completed, they are always destructed/constructed before release. For `genNotif()`, they are returned to UCX with a valid `amBuffer`. When UCX provides it again to the user, `amBuffer` is not used anymore but still allocated, so we need to free it before overwriting it.
> UCX: Fix potential memory leak with genNotif()

- .gitlab/test_python.sh
- src/api/python/_api.py
- test/python/test_nixl_api.py
Explore some extra pytest features and edge cases inside the API, with two API fixes:
The op lookup in initializing a transfer would return throw a KeyError exception, so there's no point in following it with an if statement.
Putting an empty nixlList of the wrong type into get_xfer_descs or get_reg_descs would create a seg fault, because we are dereferencing the first item in an empty list. By checking for both of these first, we can avoid this.
> pytest: add more fixtures and unit tests for API features

- src/core/nixl_agent.cpp
- src/core/nixl_listener.cpp
* NIXL_LOG doesn't require std::endl
* Replace std::cerr with NIXL_ERROR
* Avoid unnecesary copies with references and move semantics
* commThreadStop should be volatile
* Close remote sockets in Agent destructor for cleaning in case of exceptions
* Wrap static functions in nixl_listener.cpp inside unnamed namespace
> Agent: small fixes to commWorker

- examples/cpp/nixl_etcd_example.cpp
- src/api/cpp/nixl.h
- src/api/cpp/nixl_types.h
- src/core/nixl_agent.cpp
- src/core/nixl_listener.cpp
* This label is appended to the agent's key to allow custom partial MD keys in the ETCD server.
* Allows guardrailing by storing MD of different memory sections using different keys.
> Agent API: new param metadataLabel for allowing user to label md in ETCD mode

- src/utils/ucx/ucx_utils.cpp
When worker address is fetched with `UCP_WORKER_ADDRESS_FLAG_NET_ONLY` flag it does not include cuda_ipc address on the systems without MNNVL support. Also it disables some transports which may be beneficial for host memory (cma, knem)
> UCX: Fix worker address query to enable cuda-ipc

- .github/workflows/aws_efa_validation.yml
- .github/workflows/copyright-check.ps1
- .gitignore
- contrib/aws-efa/README.md
- contrib/aws-efa/aws_job_def.json
- contrib/aws-efa/aws_test.sh
- contrib/aws-efa/aws_vars.template
Add automated testing infrastructure for NIXL on AWS EFA environment via a new `contrib/aws-efa/ `module and GitHub Actions workflow.
Ensure NIXL compatibility with AWS EFA environment by:
- Automate validation for C++ and Python implementations
- Verify AWS-specific networking features
- Catche EFA-specific regressions
- Support both CI and manual testing
Implement:
- Bash testing script for job management
- AWS Batch configuration files
- New GitHub Actions workflow for PRs
- Testing on NVIDIA PyTorch containers
> CI: Add AWS EFA testing infrastructure 

- src/bindings/rust/build.rs
support for building NIXL Rust bindings on arm64 architectures. 
CARGO_CFG_TARGET_ARCH is set automatically during cargo builds
https://doc.rust-lang.org/cargo/reference/environment-variables.html
closes: #298 
closes: OPS-62
> feat: add ARM (aarch64) build support for nixl-sys

- src/api/cpp/backend/backend_engine.h
- src/api/cpp/nixl.h
- src/core/nixl_agent.cpp
- src/plugins/cuda_gds/gds_backend.cpp
- src/plugins/cuda_gds/gds_backend.h
- src/plugins/mooncake/mooncake_backend.cpp
- src/plugins/mooncake/mooncake_backend.h
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_backend.h
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- test/gtest/mocks/mock_dram_engine.cpp
- test/gtest/mocks/mock_dram_engine.h
In C++ marking method as 'const' doesn't automatically guarantee thread-safety but allows compiler to catch obvious shared state modifications which is a good first step towards making contributors consider thread safety when implementing new backends or modifying existing ones. This series marks subset of agent data path methods (reateXferReq, postXferReq, getXferStatus, releaseXferReq, genNotif) and the backend methods that they call (prepXfer, postXfer, checkXfer, releaseReqH, genNotif) as const, including laying the groundwork to make the change compile/work:
- Refactor GDS backend to extract mutable state into dedicated class that protects its data with mutex.
- Mooncake already implements its own locking. Make the lock mutable to allow taking it from const methods. Also, cosmetic …
> Mark subset of data path methods with 'const' modifier

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
- test/unit/plugins/mooncake/mooncake_backend_test.cpp
- test/unit/plugins/ucx/ucx_backend_test.cpp
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
- test/unit/utils/ucx/ucx_am_test.cpp
- test/unit/utils/ucx/ucx_worker_test.cpp
Instead of busy-polling use functionality provided by UCX that exposes file descriptors that can be monitored for events with standard UNIX APIs. Implement following changes:
- When progress thread is enabled also enable UCP feature that exposes file descriptors for wake up.
- In UCX progress thread arm every worker for wake up via file descriptor and sleep while waiting for events with poll().
- Use eventfd file descriptor to wake up the thread for cancellation.
> Refactor UCX progress thread to remove busy-polling

- src/plugins/posix/meson.build
POSIX AIO can require librt on some kernels versus Linux AIO. Fix the build script to use right library.
> plugins/posix: Fix build on RHEL8/Manylinux

- benchmark/nixlbench/contrib/Dockerfile
- benchmark/nixlbench/contrib/build.sh
Adds an option to the benchmark container build.sh script to make it possible to build from source UCX.
Rationale: it is common to need to test UCX and NIXL changes in tandem with both libraries built from source, for testing and CI. 
Example:
```bash
./benchmark/nixlbench/contrib/build.sh --ucx /path/to/ucx
```
> Benchmark: make it possible to build container with UCX built from source

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/utils/stream/metadata_stream.cpp
- test/gtest/meson.build
- test/gtest/test_transfer.cpp
When using listener thread to load remote metadata, UCX plugin fails to import some keys because the CUDA context is missing. Make sure to use one and retain it. Assumption is that we only need it when using VRAM memory, UCX anyways detects the correct device when actually using memory/keys. If no context exist/context is inactive, the retain call will keep it until backend is destroyed.
> UCX: Set a CUDA context when loading remote MD from listener thread

- src/core/nixl_listener.cpp
- test/gtest/meson.build
- test/gtest/metadata_exchange.cpp
* Before, if the remote does not exist or is never ready, the commWorker
blocks forever.
* This commit allows to try connection for 1 second and fail after
timeout.
* Also avoid throwing exception on failures during handling of remote
messages.
* New gtest fixture for metadata exchange tests using get/load and
send/fetch with sockets. ETCD mode in a separate PR.
> Agent: Bug fix: apply timeout to socket connection and add gtests for md exchange

- examples/cpp/nixl_etcd_example.cpp
- src/core/nixl_listener.cpp
* Refactor commWorker to move all ETCD functionality into new class nixlEtcdClient.
* When watching for specific key we try to fetch, avoid trying to loadRemoteMD on deletion events.
* Implement timeout when setting a watcher after trying to fetch a non-existing key.
* Setup watchers on prefix of remote agent after fetching its metadata.
* invalidateLocalMD will remove all keys with agent's prefix, then all remote watchers will be notified and invalidateRemoteMD.
* Relevant tests depend on PR [315](https://github.com/ai-dynamo/nixl/pull/315)
> Agent: Improve MD fetch and invalidate flow in ETCD mode using watchers

- examples/cpp/nixl_etcd_example.cpp
- examples/python/partial_md_example.py
- src/api/cpp/nixl.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/nixl_agent.cpp
- src/core/nixl_listener.cpp
* Enforce metadataLabel as a must for sendLocalPartialMD when sending to etcd server
* Update python API and bindings to include the label for sendLocalPartialMD and fetchRemoteMD
* Update partial_md_example.py to work with etcd when available
> Agent API: update sendLocalPartialMD to require label in etcd mode and update python bindings with label

- src/plugins/ucx_mo/ucx_mo_backend.cpp
Avoid crash in subsequent `getPublicData()` on registration failure.
> UCX_MO: Check memory registration success to avoid invalid memory access

- benchmark/nixlbench/meson.build
Currently nixlbench uses hardcoded `x86_64` path to the NIXL libraries, which makes it hard to build under arm64/aarch64.
This PR automatically detects host CPU family and uses the appropriate lib path
> nixlbench: automatically detect NIXL lib path based on host CPU

- contrib/aws-efa/aws_test.sh
Increase timeout and polling interval for AWS EFA tests.
Improve test robustness by allowing more time for concurrent AWS jobs to complete.
Reduce API call frequency and log spamming by interval spacing.
Simple parameter adjustment in the wait_for_status function:
- Timeout increased: 600s → 1800s (10min → 30min)
- Check interval increased: 60s → 180s (1min → 3min)
> CI: Increase timeout for AWS job status check

- src/plugins/hf3fs/hf3fs_backend.cpp
- src/plugins/hf3fs/hf3fs_log.h
- src/plugins/hf3fs/hf3fs_utils.cpp
* Fix missing common/status.h compile error
* add hf3fs_log.h
* add newline at end of file
* trim trailing white space
* Prefix error with HF3FS error
---------
> Fix missing common/status.h compile error in 3fs plugin - 0.3.0

- benchmark/nixlbench/contrib/Dockerfile
- benchmark/nixlbench/contrib/build.sh
- contrib/Dockerfile
- contrib/build-container.sh
- meson_options.txt
- src/plugins/cuda_gds/meson.build
Set default GDS path to point to CUDA install directory and use point lib and include to symlinks instead of hardcoding architecture-specific values.
Currently build scripts and Docker build files assume that the container is built on x86_64 Linux host (by not specifying a platform which makes docker default to host architecture, hardcoding 'x86_64' in several places, etc.), which makes it impossible to create either x86_64 or aarch64 container on Arm host or aarch64 container on x86 host.
Configure target architecture via 'ARCH' docker variable. Set it to x86 by default in docker files (for any users that use it directly) and to host architecture in build-container.sh and nixlbench build.sh. Allow user to specify ARCH value via '--arch' CLI parameter, set docker build platform value …
> Build and container fixes for aarch64

- benchmark/nixlbench/contrib/Dockerfile
- contrib/Dockerfile
This PR incorporates a few fixes:
- ARM64 fix and GDS path fix is done in https://github.com/ai-dynamo/nixl/pull/408
- Install required dependencies for IB in nixlbench Dockerfile
> nixlbench: Add deps for IB devices

- benchmark/nixlbench/contrib/Dockerfile
In PR https://github.com/ai-dynamo/nixl/pull/407 we introduced required packages for IB module of UCX to build.
However during review process I removed option `--reinstall` that is required for build to complete.
This PR adds this option back
> Fix for UCX build with IB dependencies

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- Do not duplicate AM id in the header, am id is enough to ensure proper callback is invoked on the target
- Use correct error code for UCP AM callback
[UCP API doc](https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp_def.h#L670)
> UCX: Fix UCP AM usage (do not duplicate id in the header)

- benchmark/kvbench/README.md
- benchmark/kvbench/commands/args.py
- benchmark/kvbench/commands/nixlbench.py
- benchmark/nixlbench/README.md
- benchmark/nixlbench/meson.build
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
This PR enables VMM CUDA memory allocation in NIXL to allow MNNVL communication
> nixlbench: enable VMM CUDA memory allocation

- contrib/build-container.sh
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
Set env vars in NIXL plugin for best EFA performance.
The best performance in EFA is achieved by using 4 RMA lanes, but on low message sizes this leads to significant performance degradations. Recent UCX PR (https://github.com/openucx/ucx/pull/10723) fixes this issue by adding MIN_RMA_CHUNK.
Performance impact of this change is documented here: https://confluence.nvidia.com/pages/viewpage.action?pageId=4004524984
> NIXL: set env vars for best EFA performance

- contrib/build-container.sh
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
Set env vars in NIXL UCX backend
* Best EFA performance using multiple rails and chunk sizes
* Updated UCX sha1 ref containing MIN_RMA_CHUNK
* ERROR -> WARN
* Set MDS only for UCX >= 1.19
> NIXL: set env vars for best EFA performance (#459)

- src/bindings/python/nixl_bindings.cpp
Fixed a typo resulting in a bad cast.
> Python: Fixed bad cast OBJ_SEG cast in nixl_bindings.cpp

- contrib/build-container.sh
Add the --wheel-base option to build-container.sh to specify the platform identifier used for building Python wheels e.g. manylinux_2_28.
Test pipeline: nixl-ci/30214570
> build: Add wheel-base to pass the the wheel building platform.

- benchmark/nixlbench/contrib/Dockerfile
Updates nixlbench Dockerfile to build GPUNetIO plugin correctly.
GPUNetIO plugin is part of NIXL and needs to be tested via nixlbench.
Add DOCA debians to build GPUNETIO. Add those to keep in line with the nixl container.
> nixlbench: Add GPUNETIO debs to dockerfile

- benchmark/nixlbench/contrib/Dockerfile
- contrib/Dockerfile
- contrib/Dockerfile.manylinux
Remove the lib.real from the LD_LIBRARY path
Keeping lib.real in the env var LD_LIBRARY_PATH makes a mess for the CUDA scripts to setup the symlinks for the nvidia runtime. This can cause the error 803 to be displayed.
Unfortunately, we need the libcuda.so.1 when repairing the wheel, so move the ENV command there and restore the old LD_LIBRARY_PATH after finishing.
> contrib: Remove the lib.real from the LD_LIBRARY path

- benchmark/nixlbench/contrib/Dockerfile
- contrib/Dockerfile
- contrib/Dockerfile.manylinux
Dont include libcuda.so.1 in the nixl wheel.
libcuda.so.1 should be excluded from wheels due to compatibility issues. It isnt required to build since meson finds the stubs and links against them. On the host it should find the cuda driver library and use that.
Update dockerfiles used to generate wheels.
> contrib: Clean up libcuda.so.1

- .clang-format
- .pre-commit-config.yaml
Adds .clang-format file. Disable clang formatter in pre-commit until the CI clang format checker is ready.
Required for formatting code correctly.
> clang: Add clang format file

- benchmark/nixlbench/contrib/Dockerfile
Updates nixlbench Dockerfile to build GPUNetIO plugin correctly.
GPUNetIO plugin is part of NIXL and needs to be tested via nixlbench.
Add DOCA debians to build GPUNETIO. Add those to keep in line with the nixl container.
> nixlbench: Add GPUNETIO debs to dockerfile - 0.3.1

- .gitlab/test_python.sh
- src/bindings/python/nixl_bindings.cpp
- src/infra/nixl_descriptors.cpp
In python bindings - warn when an xferDList / regDList is created with sorted=True while it's not sorted
We had an assertion for that, but they are not active in release builds.
Nixl would print a warning message and treat the descriptors list as not sorted
> SRC/BINDINGS/PYTHON: Fix handling of unsorted desc list passed with sorted=True

- contrib/Dockerfile.manylinux
Use newer SSL for building the wheel, but remove the binaries from packaging
The base image has a very old version
> Upgrade ssl dependency for wheel

- contrib/Dockerfile.manylinux
- contrib/wheel_add_ucx_plugins.py
* UCX transport modules are now packaged correctly in the wheel (previously missing)
Fixes NIX-100 and issue #334 
The wheel is a zip archive that contains the nixl code and some dependencies that are also packaged.
The previous wheel did not bundle the UCX transport modules.
The transport modules were not bundled because the bundling step is done by the `auditwheel repair` command, which pulls into the wheel all the libraries linked against from the base system. However, the UCX transport modules are not linked directly, instead loaded at runtime by UCX through dlopen.
To add the transport modules, we copy them into the wheel in a ucx subdirectory relative to the libs directory where the main UCX libs are located (this is important, because that is how UCX is loading the modules) and we …
> Add missing UCX plugins to python wheel (#483)

- contrib/Dockerfile.manylinux
Use newer SSL for building the wheel, but remove the binaries from packaging
The base image has a very old version. Fixes NIX-120.
> Upgrade ssl dependency for wheel (#488)

- contrib/wheel_add_ucx_plugins.py
Compress wheels after patching.
`auditwheel repair` uses DEFLATE compression explicitly: https://github.com/pypa/auditwheel/blob/112180fbcce8112e8c262d2704c9f625156d59cc/src/auditwheel/tools.py#L148
We added an additional step that uses `zipfile.ZipFile` without specifying the compression method and level explicitly. By default it uses stored (no compression) and the wheel file grew from ~30 MB to 99 MB.
We should use compression the same as auditwheel.
Wheel size dropped to 28 MB.
> Compress wheel

- contrib/wheel_add_ucx_plugins.py
Compress wheels after patching.
`auditwheel repair` uses DEFLATE compression explicitly: https://github.com/pypa/auditwheel/blob/112180fbcce8112e8c262d2704c9f625156d59cc/src/auditwheel/tools.py#L148
We added an additional step that uses `zipfile.ZipFile` without specifying the compression method and level explicitly. By default it uses stored (no compression) and the wheel file grew from ~30 MB to 99 MB.
We should use compression the same as auditwheel.
Wheel size dropped to 28 MB.
> Compress wheel (#497)

- src/core/nixl_agent.cpp
- src/plugins/ucx/ucx_backend.cpp
- test/gtest/test_transfer.cpp
Added support for self notification for UCX backend, which is requested by TensorRT-LLM team.
Currently NIXL agent supports transfer Request to itself, but doesn't support genNotif to itself.
Without this option they have to use fake transfer request with notification as a workaround.
- Changed genNotif to check for local name
- Few optimisations to avoid redundant string copies
- Few optimisations to avoid heap allocation/deallocation
- Added test for UCX backend
> NIXL/UCX: Added support for self notification

- examples/cpp/nixl_example.cpp
Removed `#include "ucx_backend.h"`.
https://github.com/ai-dynamo/nixl/issues/442
> EXAMPLES/CPP: Fixed includes.

- contrib/aws-efa/aws_test.sh
Removes automatic retry on AWS job failures, adds GitHub metadata tags for traceability, and improves diagnostics when jobs fail to start.
- Failed tests were retrying 3 times, wasting AWS resources
- No way to link AWS jobs back to GitHub Actions runs
- No visibility into why jobs get stuck in RUNNABLE state
- Remove `--retry-strategy '{"attempts":3}'` 
- Add tags with GitHub context and direct link to Actions run
- Show job status/reason on startup timeout
```
$ aws batch describe-jobs --jobs "$JOB_ID" --query 'jobs[0].tags' --output table
-------------------------------------------------------------------------------------
|                                   DescribeJobs                                    |
+--------------------+---------------------------------------------------------- …
```
> AWS: Remove job retries and add GH metadata tags

- .gitignore
- contrib/Dockerfile
- src/core/meson.build
- src/core/nixl_plugin_manager.cpp
- src/plugins/meson.build
- src/plugins/obj/README.md
- src/plugins/obj/meson.build
- src/plugins/obj/obj_backend.cpp
- src/plugins/obj/obj_backend.h
- src/plugins/obj/obj_executor.h
- src/plugins/obj/obj_plugin.cpp
- src/plugins/obj/obj_s3_client.cpp
- src/plugins/obj/obj_s3_client.h
- subprojects/asio.wrap
- test/gtest/meson.build
- test/gtest/unit/main.cpp
- test/gtest/unit/meson.build
- test/gtest/unit/obj/meson.build
- test/gtest/unit/obj/obj.cpp
- test/nixl/test_plugin.cpp
Implement OBJ storage plugin for AWS S3 generic objects and accompanying tests.
NIXL needs a plugin that can handle OBJ_SEG memory type. AWS S3 seems like an obvious first choice and meets customer demands.
Use AWS SDK async API for performance. Provide S3Client with executor based on Asio thread pool to establish an upper bound of resource usage (number of threads).
Validate the functionality with new Gtest-based _unit_ tests with mocked S3 wrapper. The tests don't have any external dependencies and can be executed with sanitizers enabled.
> Object storage plugin

- src/utils/ucx/config.cpp
- src/utils/ucx/config.h
- src/utils/ucx/meson.build
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
Added ucx::Config class.
Applied RAII style.
Fixed memory leak in case of the `ucp_init` failure.
Added error handling of `ucp_config_read`.
Better resource management and error handling.
I've introduced new namespaces. And I'd also like to change `class nixlUcxContext`, `class nixlUcxWorker`, etc. to `class Context`, `class Worker`, etc. in `namespace nixl::ucx`
> UTILS/UCX: Added ucx::Config class.

- src/plugins/cuda_gds/gds_backend.cpp
Exceeding number of batches can cause the GDS batches to run out of memory. Decreasing the default number of GDS batches created to facilitate creating multiple NIXL agents.
This PR is trying to reduce the default number of GDS batches as it can affect the number of NIXL agents that can be created as GDS batches in pool consume memory.
Required for KVBM G3 use case where TP8 is a requirement.
Simple change to modify the default number of batches created at init.
> cuda_gds: Reducing the number of default batches created to 16

- contrib/Dockerfile.manylinux
Currently the wheel is built and published only for x86_64. Add support for ARM 64.
Tested: wheel build + pip install on nvcr.io/nvidia/cuda-dl-base:25.03-cuda12.8-devel-ubuntu24.04 + examples/python/nixl_api_example.py on x86_64 and aarch64.
> Add support for building python wheel on ARM 64

- src/utils/ucx/ucx_utils.cpp
Just print a warning when VRAM memory is not detected properly
Wrong memory detection does not affect all uses-cases, sometimes it can work for inter-node jobs
> UCX: Do not fail registration in mem check

- src/plugins/ucx/ucx_backend.cpp
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
- test/gtest/error_handling.cpp
enable error handling mode peer by default in UCX backend
better error handling support
> BACKEND/UCX: enable error handling mode peer by default

- .clang-tidy
Create a config file for clang-tidy tool in order to enforce naming style of types, functions, and variables according to NIXL code style.
Both [internal](https://github.com/ai-dynamo/nixl/pull/559#discussion_r2202896758) and [external](https://github.com/ai-dynamo/nixl/pull/494#discussion_r2167340898) contributors have often been naming types, functions, and variables incorrectly. Moreover, due to complex NIXL naming conventions these mistakes often slip past code review.
Clang-tidy is a tool readily available in Ubuntu and other distro's repositories similarly to clang-format that is already used by NIXL. Excerpt from the tool output with provided config on a NIXL source:
```
../../home/vladbu/src/nixl/src/plugins/ucx/ucx_backend.cpp:236:59: warning: invalid case style for parameter …
```
> clang-tidy: Add config to enforce naming style

- src/core/nixl_plugin_manager.cpp
The dladdr error check is inverted
dladdr returns 0 on error and 1 on success.
> Fix plugin path lookup

- benchmark/kvbench/commands/args.py
- benchmark/kvbench/commands/nixlbench.py
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
- benchmark/nixlbench/src/runtime/etcd/python_bindings.cpp
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/worker.cpp
Allows multiple benchmarks to be executed at the same time.
Adds benchmark name to use separate namespaces for all metadata keys.
> Add support for parallel nixlbench tests

- .ci/jenkins/pipeline/proj-jjb.yaml
Improves developer experience by providing clickable links to failed child jobs (build/test) directly from the dispatcher job description.
Improve CI user experience
We want to have 1 click simple access to dispatcher child job results
By adding html clickable url links in the dispatcher build page
> ci: Add direct links to child jobs in dispatcher build description

- src/plugins/obj/README.md
- src/plugins/obj/obj_s3_client.cpp
Allow users to configure AWS Request checksum setting.
Some users encountered issues with using Obj plugin with endpoints that don't support STREAMING-UNSIGNED-PAYLOAD-TRAILER.
Via plugin custom params.
Fixes NIX-205
> obj: Add request checksum config toggle

- CODEOWNERS
Make sure a either a maintainer or a designated code owner approves any PR
> CODEOWNERS: Set default code owners to maintainers team

- src/plugins/meson.build
- src/plugins/ucx/ucx_backend.cpp
- test/unit/utils/ucx/ucx_worker_test.cpp
Remove unneeded header. Also extend build gds plugin flag to gds_mt.
Cufile isnt required by UCX plugin/test.
> plugins/ucx: Remove leftover cufile header

- benchmark/nixlbench/meson.build
Meson's library install results in different paths:
Ubuntu: lib/x86-64-linux-gnu
RHEL: lib64
Don't assume we are on Ubuntu. Otherwise, linking fails on Red Hat.
> fix: don't assume on library path construction in meson build file

- src/plugins/obj/obj_backend.cpp
Fixed a bug in the registerMem function of the OBJ plugin.
The previous implementation didn’t handle the metadata pointer correctly for memory types other than OBJ, potentially leaving it uninitialized. This could result in a segmentation fault during nixlObjEngine::deregisterMem when attempting to access it.
Explicitly set metadata output to nullptr for non-OBJ memory types to avoid undefined behavior.
> Fix issue in registerMem for OBJ plugin

- examples/python/partial_md_example.py
Fixing partial_md_example.py
The test had 2 main issues:
1. Sending target_xfer_descs1 instead of target_xfer_descs2
2. Setting `is_sorted=True` while descriptors are not sorted by address, I set the flag to False. We can alternatively sort descriptors by address
> EXAMPLES/PYTHON: partial md example - fix test logic and warnings

- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Cherry pick of https://github.com/ai-dynamo/nixl/pull/637
The regression is introduced in https://github.com/ai-dynamo/nixl/pull/607, which leads to segfault, and nixlbench is not usable for non OBJ/storage use cases
remote_iovs are not populated in non OBJ/storage use cases
```
basic_desc.value().metaInfo = remote_iovs[list_idx][i].metaInfo;
```
> NIXLBENCH: Fix memory allocation for non OBJ/storage use case (#637) - 0.5.0

- contrib/Dockerfile
Cherry-pick of https://github.com/ai-dynamo/nixl/pull/642
The rust build scripts assume that NIXL_PREFIX env var is present. We should export it in the Dockerfile.
> RUST: Fix cargo package

- src/plugins/cuda_gds/meson.build
- src/plugins/gds_mt/meson.build
- src/plugins/gpunetio/meson.build
- src/plugins/hf3fs/meson.build
- src/plugins/mooncake/meson.build
- src/plugins/obj/meson.build
- src/plugins/posix/meson.build
- src/plugins/ucx/meson.build
- src/plugins/ucx_mo/meson.build
Cherry-pick of #612
---------
Set rpath to $ORIGIN (plugin dir) and $ORIGIN/.. (nixl lib dir) for all plugins
Some of the plugins do not load in the TRT-LLM image because LD_LIBRARY_PATH is not set to include the nixl directory; and some also need the plugin directory. But LD_LIBRARY_PATH should not be needed. Only the main nixl libs must be loadable; then when they dlopen() the plugins, the dependencies should be resolved automatically.
We set both current dir and parent dir because some plugins depend on other plugins; and all plugins depend on the nixl libs from the parent dir.
> Plugins should set rpath so that they can load their dependencies (#612)

- benchmark/nixlbench/contrib/Dockerfile
Fixes a dependency installation which was incorrectly hardcoded for x86_64.
> NIXLBENCH: Install arch specific AWS CLI

- benchmark/nixlbench/contrib/Dockerfile
Cherry pick of #650
Fixes a dependency installation which was incorrectly hardcoded for x86_64.
> NIXLBENCH: Install arch specific AWS CLI - 0.5.0

- test/gtest/test_transfer.cpp
> NIXL/GTEST: remove dead code

- .gitlab/build.sh
- benchmark/nixlbench/contrib/Dockerfile
- contrib/Dockerfile
- contrib/Dockerfile.manylinux
Use shallow clones wherever possible, for faster checkout using less traffic.
To speed up container builds and CI runs.
The main problem is the AWS SDK which is a very large repo:
Full clone takes 3 minutes:
```
time git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git --branch 1.11.581
...
276.92s user 93.36s system 195% cpu 3:09.33 total
```
Shallow clone takes 1.5 minutes:
```
time git clone --recurse-submodules --depth 1 --shallow-submodules https://github.com/aws/aws-sdk-cpp.git --branch 1.11.581
...
25.35s user 16.80s system 45% cpu 1:33.38 total
```
The other git clones have a smaller impact.
I did not do this for UCX because:
* git clone --branch X does not accept hashes and we might need that for UCX
* a full clone of UCX takes 7 seconds so there is not much to …
> Use shallow clones in scripts if possible

- src/core/nixl_listener.cpp
Fixed stack smashing detected crash in connectToIP() by replacing `select()` with `poll()`.
The `select()` system call crashes when file descriptors exceed `FD_SETSIZE (1024)`. The crash occurred when `connectToIP()` received `fd>1024`, causing `FD_SET()` to write beyond the `fd_set` structure bounds.
According to the Linux manual: "All modern applications should instead use poll(2) or epoll(7), which do not suffer this limitation."
https://man7.org/linux/man-pages/man2/select.2.html
Replaced `select()` with `poll()` using` POLLOUT event` and `1000ms` timeout. Maintains identical functionality while supporting unlimited file descriptor numbers.
> Bugfix: Replace select() with poll() in connectToIP to prevent stack smashing

- src/plugins/posix/posix_backend.cpp
Fix POSIX queue type messages
Use to_string to convert queue type correctly.
Running nixl_posix_test you can now see:
```
export NIXL_LOG_LEVEL=INFO
============================================================
NIXL STORAGE REPOST TEST STARTING (POSIX PLUGIN)
============================================================                                                                  
I0814 11:02:21.840475 3267797 posix_backend.cpp:212] POSIX backend initialized using queue type: URING
```
> plugins/posix: Fix queue type message

- examples/python/query_mem_example.py
The changes in PR 573 exposes an issue in query_mem examples, fixed it so CI can pass.
> query_mem example fix

- .gitlab/build.sh
Adds missing dependency in tests
common.sh script uses the `ss` utility from iproute2 package to find unused port numbers for etcd:
```
while ss -tuln | grep -q :$next_port; do
next_port=$((next_port + 1))
done
```
Currently it is not always installed, so there are some errors logged in the CI
> CI: Add iproute2 dependency

- src/plugins/obj/obj_plugin.cpp
Cherry-pick of #703 
All mandatory Obj parameters can be provided via environment variables and don't have a real defaults (key, token, etc.). Defaults for optional parameters are already handled by the plugin itself.
The current values in the default backend parameters map are wrong since they should be the default values that plugin accepts during initialization, not description strings. Return and empty map instead.
> OBJ: Remove backend options from default params map (#703)

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/utils/ucx/ucx_utils.cpp
- test/gtest/error_handling.cpp
- initialize `req->conn` in `checkXfer`
- added a test
- more few fixes with the new test
- Fix for https://nvbugspro.nvidia.com/bug/5472171
- Close the debt https://github.com/ai-dynamo/nixl/pull/677#discussion_r2277670415
- https://github.com/ai-dynamo/nixl/pull/690#pullrequestreview-3127128611
move connection lookup to a helper method `getConnection` and pass the result to `notifSendPriv`
> BACKEND/UCX: fix req initialization in checkXfer

- src/plugins/cuda_gds/gds_utils.cpp
Cherry-pick of #721 
Zero out CUfileDescr_t before calling cuFileHandleRegister to prevent a segmentation fault
> [GDS] bugfix - initialize CUfileDescr_t (#721)

- benchmark/kvbench/pyproject.toml
- benchmark/nixlbench/README.md
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Checks if an IO request's offset is within the allocated buffer limit. 
Update a function's definition based on value passed. Update README for nixlbench. 
Remove the numpy version in kvbench since that version requires 3.11 python. Appropriate version will be auto selected.
> NIXLBench: Check individual thread buffer size

- benchmark/kvbench/pyproject.toml
- benchmark/nixlbench/README.md
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Checks if an IO request's offset is within the allocated buffer limit. 
Update a function's definition based on value passed. Update README for nixlbench. 
Remove the numpy version in kvbench since that version requires 3.11 python. Appropriate version will be auto selected.
> NIXLBench: Check individual thread buffer size (#726)

- src/api/cpp/nixl_descriptors.h
To separate clang formatting from PR 731
> clang format the nixl_descriptors header

- contrib/build-wheel.sh
Adjust wheel library filter to exclude more CUDA libraries.
GDS plugin was pulling libcudart and libcufile into the wheel.
> Do not bundle libcuda* and libcufile into the wheel

- meson.build
Add manual CUDA detection as a fallback in meson build script for NIXL.
Seeing that on lego and some other ARM hosts (but not all images), the builtin CUDA detection of meson does not find libcudart. This is due to missing pkg-config files in the base image.
Before:
```
#26 24.03 Run-time dependency CUDA (modules: cudart, cuda) found: NO (tried system)
```
After:
```
#26 24.03 Run-time dependency CUDA (modules: cudart, cuda) found: NO (tried system) <<<< THIS IS MESON
#26 24.03 WARNING: You should add the boolean check kwarg to the run_command call.
#26 24.03          It currently defaults to false,
#26 24.03          but it will default to true in meson 2.0.
#26 24.03          See also: https://github.com/mesonbuild/meson/issues/9300
#26 24.03 Message: CUDA root: /usr/local/cuda
#26 …
```
> Fallback to manual CUDA detection when meson detection fails

- src/api/cpp/backend/backend_engine.h
- src/api/cpp/nixl.h
- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
Adds host-side API for GPU transfer request.
To establish foundation for GPU-initiated transfers.
See also: https://github.com/ai-dynamo/nixl/pull/704
- Added two new virtual methods to nixlBackendEngine interface:
- `createGpuXferReq()`: Creates a GPU transfer request handle to GPU memory
- `releaseGpuXferReq()`: Releases a GPU transfer request from GPU memory
- Implemented public API methods in `nixlAgent` with parameter validation and thread safety
- Added UCX backend stubs for compatibility
- Included API documentation
> Create host-side GPU transfer request API

- .ci/jenkins/lib/build-container-matrix.yaml
Fix Nixl image build job for verification
Images built with this job stop working for verification needs - starting the image without arguments failed
Change the way we create the image and adding the version file into it.
> CI: Build container job fixup

- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
Fix an issue where target stuck at waiting for more data from initiator due to wrong expectation
warm up iterations used in initiator is per thread, so target have to multiply that by thread.
> Fix Error in barrier when testing block size above 1M

- .github/workflows/blossom-ci.yml
We want to avoid having to add /build comment to trigger blossom CI. This will true only for branches:
- release/*
- main
Update blossom-ci workflow to avoid having to add comment in order to trigger it
Improve usability for blossom ci
New feature was enabled in Blossom ci
> CI: avoid /build comment to trigger blossom-ci

- src/infra/nixl_memory_section.cpp
- test/nixl/agent_example.cpp
Improve populate method performance for not fully sorted inputs.
In some use cases the input is not fully sorted, but has chunks of sorted regions. Also this removes the need from user indicating and making sure the input is sorted, as benefits become very marginal.
- Find the first element in LogN search time. Then assume it's sorted unless it is not, and search for that non-conforming element in LogN search time.
- Replaced check for nixl_sec_dlist_t to be sorted with assert as it should always be.
- For fully sorted lists this would add one extra check.
> Improve populate method performance for not fully sorted inputs.

- contrib/Dockerfile
- contrib/Dockerfile.manylinux
Upgrade DOCA from 3.0 to 3.1 in contrib and manylinux Dockerfiles
This also enables gpunetio plugin building and packaging in the python wheel
Build was broken with CUDA 13 base image (nvcr.io/nvidia/cuda-dl-base:25.08-cuda13.0-devel-ubuntu24.04) because the base image already bundles DOCA 3.1.
> Upgrade DOCA to 3.1 in Dockerfiles

- .gitlab/test_cpp.sh
- .gitlab/test_python.sh
- docs/telemetry.md
- src/api/cpp/nixl.h
- src/api/cpp/nixl_types.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/core/telemetry.cpp
- src/core/telemetry.h
- src/core/telemetry_event.h
- src/core/transfer_request.h
- test/gtest/telemetry_test.cpp
- test/gtest/test_transfer.cpp
- test/python/test_nixl_api.py
- test/python/test_nixl_bindings.py
Add getXferTelemetry API to nixl Agent.
Another mode of outputting telemetry, getting information per xfer_req.
> Agent: Add getXferTelemetry API.

- benchmark/kvbench/pyproject.toml
- benchmark/nixlbench/contrib/Dockerfile
Force installation of pytorch with CUDA support in nixlbench container image.
Also relaxed the torch version pin in kvbench, since we do not need exactly 2.7.0 and it varies depending on CUDA version.
Tested with x86-64 and aarch64 images built in CI pipeline. Both changes are needed.
Ensure that GPU-enabled torch is selected in CI builds on ARM.
Until now, we were relying on meson to install pytorch. Selection of the variant with CUDA support worked reliably on x86_64; on ARM, it installs the CPU version.
This is a blocker for verification team, that needs torch to work out of the box with CUDA support in order to execute some of the tests in automation without any image changes.
> Nixlbench: Install torch with CUDA support

- .github/workflows/blossom-ci.yml
This reverts commit 531e8038f80a89ca295049ca32a24b31b5f1d52b.
Revert previous blossom-ci avoid comment change
This feature is broken from Blossom side and they need to fix it, to avoid check failures we need to revert back to original state
> Revert "CI: fix for blossom-ci auto trigger without comment (#771)"

- benchmark/kvbench/pyproject.toml
- benchmark/nixlbench/contrib/Dockerfile
Force installation of pytorch with CUDA support in nixlbench container image.
Also relaxed the torch version pin in kvbench, since we do not need exactly 2.7.0 and it varies depending on CUDA version.
Tested with x86-64 and aarch64 images built in CI pipeline. Both changes are needed.
Ensure that GPU-enabled torch is selected in CI builds on ARM.
Until now, we were relying on meson to install pytorch. Selection of the variant with CUDA support worked reliably on x86_64; on ARM, it installs the CPU version.
This is a blocker for verification team, that needs torch to work out of the box with CUDA support in order to execute some of the tests in automation without any image changes.
> Nixlbench: Install torch with CUDA support (#758)

- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- src/core/nixl_agent.cpp
- test/gtest/error_handling.cpp
Fix use after free after disconnect.
Some agent methods such as postXferReq, getXferStatus, were on error deleting the request received as argument despite not having ownership.
The request was deleted on some error paths but not all.
The deletion should be initiated by the client through the releaseXferReq API.
This was caught when we introduced destructors for the request handles in Python. Until now, handles were being leaked.
> CORE: Do not delete requests unless we own them (#782)

- benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.h
is PR fixes a build failure in nixlbench when building the NVSHMEM worker.
● The header previously declared exchangeIOV with a single argument, marked override.
● The source defined exchangeIOV with two arguments (const std::vector<std::vector<xferBenchIOV>>&, size_t).
● This mismatch caused a compiler error about the method not actually overriding a base class function.
🔧 Change:
The header declaration has been updated to match the definition (two arguments).
Nixlbench-build succeeds with NVSHMEM enabled, and xferBenchNvshmemWorker now has a consistent interface.
> Fix signature mismatch in xferBenchNvshmemWorker::exchangeIOV

- test/unit/utils/meson.build
Fix build regression.
Missing check for libfabric dependency.
> Fix build when libfabric is not installed

- src/api/gpu/ucx/nixl_device.cuh
Following https://github.com/openucx/ucx/pull/10895, added `nixlGpuWriteSignal` API function to enable writing values to local GPU signals.
Provides write capability in addition to the existing `nixlGpuReadSignal` function, enabling complete signal manipulation from GPU device code using the underlying UCX `ucp_device_counter_write` functionality.
Implemented as a templated device function following existing NIXL GPU API patterns, with support for different cooperation levels (THREAD, WARP, BLOCK, GRID) and proper UCX level conversion.
> DEVICE/API: Add nixlGpuWriteSignal API for local signal writing

- src/plugins/libfabric/libfabric_backend.cpp
- src/utils/libfabric/libfabric_rail.cpp
This PR implements direct memory copy (memcpy) for transfers within the same agent to avoid unnecessary network operations. It also adds comprehensive debug logging for transfer path selection and agent comparison to help diagnose transfer routing decisions.
Currently, same-agent transfers (when both source and destination are within the same agent process) are failing with `agent_example.sh` because the system attempts to use network-based transfers through libfabric even when both memory regions are local to the same process. This results in:
- Connection handshake failures between local endpoints
- Transfer failures with errors like "Unresponsive receiver" and "Software caused connection abort"
The root cause is that the current transfer path selection logic in …
> Add same-agent transfer optimization with memcpy fallback

- src/bindings/rust/src/agent.rs
- src/bindings/rust/stubs.cpp
- src/bindings/rust/tests/tests.rs
- src/bindings/rust/wrapper.cpp
- src/bindings/rust/wrapper.h
Rust API:
- Add ThreadSync and AgentConfig (with Default)
- Add Agent::new_configured(name, &AgentConfig) alongside existing Agent::new
> Add agent configuration support to Rust bindings

- src/utils/libfabric/libfabric_common.h
- src/utils/libfabric/libfabric_rail.cpp
- src/utils/libfabric/libfabric_rail_manager.cpp
Fix libfabric backend retry failures in test_nixl_bindings.py some of the tests are failing execution with memory double free error.
Currently fi_writedata retry logic only existis with tcp provider.
Upon inspection, we found that we need to do retries even with efa provider.
This PR implements retires with EFA provider and address some potential double free resources.
> Fix libfabric double-release and resource cleanup issues

- benchmark/nixlbench/contrib/Dockerfile
Cherry-pick of #845
Activate virtual environment explicitly in nixlbench container
Python3 should work out of the box when a shell is opened.
```
$ docker images
REPOSITORY                                                           TAG                                                                                    IMAGE ID       CREATED          SIZE
nixlbench                                                            v0.6.0.dev.bc2c2c19                                                                    755bf7ea398d   23 minutes ago   28GB
$ docker run -it 755bf7ea398d python3
==========
== CUDA ==
==========
NVIDIA Release  (build )
CUDA Version 12.9.1.010
Container image Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Various files include modifications (c) …
```
> Activate venv in nixlbench container (#845)

- .ci/jenkins/pipeline/proj-jjb.yaml
Change the job's url in dispatcher job to blue ocean to avoid the extra click on the "Blue Ocean" button.
Improve CI user experience
Change child jobs url in dispatcher job
> CI: improve blossom job user experience

- src/utils/libfabric/libfabric_common.h
- src/utils/libfabric/libfabric_rail.cpp
- src/utils/libfabric/libfabric_rail_manager.cpp
Cherry-pick of #839
Fix libfabric backend retry failures in test_nixl_bindings.py some of the tests are failing execution with memory double free error.
Currently fi_writedata retry logic only existis with tcp provider.
Upon inspection, we found that we need to do retries even with efa provider.
This PR implements retires with EFA provider and address some potential double free resources.
> Fix libfabric double-release and resource cleanup issues (#839)

- src/utils/libfabric/libfabric_common.h
- src/utils/libfabric/libfabric_rail.cpp
We retry indefinitely in the case of FI_EGAIN until operation succeeds or fails.
Log every 100 attempts to avoid log spam. Added exponential backoff with cap to prevent system overload.
This attempts to resolve 'Resource temporarily unavailable' errors even after 10 retries.
> [Libfabric]: retry operations

- benchmark/nixlbench/README.md
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- benchmark/nixlbench/src/worker/worker.cpp
Make etcd runtime optional when running storage backends for nixlbench. 
Storage backends run in loopback mode and do not exchange metadata between instances. This makes etcd endpoints optional for storage. Nixlbench for storage backends can still be run with etcd to synchronize across multiple instances if required.
Allows simple nixlbench instances to run quickly without starting an etcd server.
> nixlbench: Make etcd optional for storage backends

- .ci/scripts/common.sh
- .gitlab/test_cpp.sh
- .gitlab/test_python.sh
- contrib/aws-efa/aws_vars.template
- examples/cpp/nixl_example.cpp
- src/utils/libfabric/libfabric_topology.cpp
- test/nixl/agent_example.cpp
- test/python/conftest.py
- test/python/test_nixl_api.py
Added backend selection option to some of the tests.
Added TEST_LIBFABRIC env var to AWS EFA tests, set to true. Defaults to false in other tests (where it is unset). Prevents running libfabric tests on platforms without support.
Now we can test new backends such as libfabric.
> [Test/Example] Added backend selection option for libfabric unit tests
