ai-dynamo/nixl

- src/plugins/cuda_gds/gds_backend.cpp
Fix uninit values in plugin.
Rlease build works.
> plugins/cuda_gds: Fix release build

- util/build.sh
- util/test_cpp.sh
- util/test_python.sh
> ci: Added ucx_mo_backend_test.

- src/core/nixl_plugin_manager.cpp
- src/plugins/ucx_mo/meson.build
- src/plugins/ucx_mo/ucx_mo_plugin.cpp
- test/nixl/test_plugin.cpp
UCX_MO as a static plugin should be found correctly. 
Also, python tests should find UCX and build pip correctly.
> nixl/plugins: Fix static plugins and tests

- src/core/nixl_agent.cpp
* To avoid keeping track of transfers per remote agent, instead if it was used within a transfer call, it'll get to error state.
* Using a hash map from remote name to a pointer, this check will have minimal overhead.
* Also a minor bug fix for deregisterMem when backends are autodetected.
> Agent: Added checks for remote being removed in transfer methods 

- src/core/nixl_agent.cpp
Update the agent code to try to cancel in progress requests but return an error if they can't be cancelled.
Currently untested as we don't have a backend that will fail during request cancel (UCX will always "succeed", GDS will block until complete or cancelled).
> agent: better canceled req handling

- src/plugins/cuda_gds/gds_backend.cpp
> GDS backend: improved clean ups

- meson.build
- pyproject.toml
Update version numbers and pyproject options in preparation of next release.
> release: prep for v0.1.1

- examples/python/nixl_gds_example.py
- src/api/python/_api.py
- src/plugins/cuda_gds/gds_backend.cpp
- src/plugins/cuda_gds/gds_backend.h
- src/plugins/cuda_gds/gds_plugin.cpp
- src/plugins/cuda_gds/gds_utils.cpp
- src/plugins/cuda_gds/gds_utils.h
- src/plugins/cuda_gds/meson.build
- test/unit/plugins/cuda_gds/nixl_gds_test.cpp
Duplicate of #114 for release branch
> GDS: backend improvements and new tests

- src/api/cpp/nixl.h
- src/api/cpp/nixl_types.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/nixl_agent.cpp
Duplicate of #127 for release branch
> Doxygen: Update Python API with comments and minor improvements

- .github/copy-pr-bot.yaml
Breaking  PR143 into two pieces to trigger the CI appropriately
> feat: enable copy-pr-bot

- src/plugins/cuda_gds/gds_backend.cpp
Post requires IN_PROG for latest agent.
Updating checkXfer accordingly.
> cuda_gds Minor fix on how to set the return on post

- README.md
- contrib/README.md
In python world, conda env is widely used it offers clean dependency management & isolation.  I managed to build, install & run llm using ai_dynamo_vllm in my local conda env for dev & testing. Works well on `Ubuntu 22.04.5 LTS` too.
- https://github.com/ai-dynamo/dynamo (https://github.com/ai-dynamo/dynamo/pull/478)
- https://github.com/ai-dynamo/nixl (This PR)
> README: update with instructions for build & install in a conda env

- meson_options.txt
- test/gtest/main.cpp
- test/gtest/meson.build
- test/gtest/mocks/meson.build
- test/gtest/mocks/mock_basic_plugin.cpp
- test/gtest/mocks/mock_dram_engine.cpp
- test/gtest/mocks/mock_dram_engine.h
- test/gtest/mocks/mock_dram_plugin.cpp
- test/gtest/plugin_manager.cpp
This PR initializes the testing infrastructure using Google Test and sets up the foundation for plugin support, including basic configuration and mock components
> testing: gtest initial infrastructure

- .gitlab/test_cpp.sh
Run the plugin test within CI.
> CI: Add plugin test

- .gitlab/test_python.sh
- examples/python/blocking_send_recv_example.py
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/agent_data.h
- src/core/nixl_listener.cpp
Extend the new NB APIs for metadata exchange to the python API, with updated example
> python API: add metadata exchange calls

- src/core/nixl_agent.cpp
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- test/unit/plugins/ucx/ucx_backend_test.cpp
- test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
> backend:ucx: Implement handler reuse

- .gitlab/test_python.sh
- examples/python/partial_md_example.py
- src/api/cpp/nixl.h
- src/api/cpp/nixl_types.h
- src/api/python/_api.py
- src/bindings/python/nixl_bindings.cpp
- src/core/agent_data.h
- src/core/nixl_agent.cpp
- src/core/nixl_listener.cpp
- test/nixl/nixl_test.cpp
- Add sendPartialLocalMD to API in both C++ and Python
- Add getPartialLocalMD API to Python
- New test for sending/transferring with partial metadata
> API: sendPartial and python API updates

- src/core/nixl_plugin_manager.cpp
We can now use C++17 filesystem apis for checking the plugin files and directories.
> plugin_mgr: Use filesystem from C++17

- benchmark/nixlbench/README.md
- benchmark/nixlbench/contrib/Dockerfile
- benchmark/nixlbench/contrib/build.sh
- benchmark/nixlbench/meson.build
- benchmark/nixlbench/meson_options.txt
- benchmark/nixlbench/src/main.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
- benchmark/nixlbench/src/runtime/etcd/meson.build
- benchmark/nixlbench/src/runtime/meson.build
- benchmark/nixlbench/src/runtime/runtime.cpp
- benchmark/nixlbench/src/runtime/runtime.h
- benchmark/nixlbench/src/utils/meson.build
- benchmark/nixlbench/src/utils/scope_guard.h
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/meson.build
- benchmark/nixlbench/src/worker/nixl/meson.build
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- benchmark/nixlbench/src/worker/nixl/nixl_worker.h
- benchmark/nixlbench/src/worker/nvshmem/meson.build
- benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
- benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.h
- benchmark/nixlbench/src/worker/worker.cpp
- benchmark/nixlbench/src/worker/worker.h
Internal git SHA: ffb61b23315fc24154c206c38383c7beccdf4c10
Co-authored-by: Adit Ranadive <aranadive@nvidia.com>
Co-authored-by: Artem Y. Polyakov <artemp@nvidia.com>
Co-authored-by: Vishwanath Venkatesan <vvenkatesan@nvidia.com>
Co-authored-by: Vlad Buslov <vladbu@nvidia.com>
Co-authored-by: Subhadeep Bhattacharya <subhadeepb@nvidia.com>
Signed-off-by: Subhadeep Bhattacharya <subhadeepb@nvidia.com>
> NIXLBench: Initial squashed commit for NIXLBench

- src/core/nixl_listener.cpp
When receiving INVL command from peer the connection socket is closed and removed from remoteSockets map. However, since command processing is performed inside an outer loop over remoteSockets, the removal also invalidates the outer loop iterator which causes a segfault[0].
Fix the issue by refactoring the loop to assign the new iterator value returned by map::erase() to the outer loop iterator.
[0]:
0x00007f84efb46154 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /lib/x86_64-linux-gnu/libstdc++.so.6 0x00007f84efdfdf87 in std::_Rb_tree_iterator<std::pair<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const, int> >::operator++ (this=0x7f84ef731bc8) at /usr/include/c++/13/bits/stl_tree.h:287
0x00007f84efdfd0cb in …
> Fix iteration over remoteSockets during invalidation

- examples/python/blocking_send_recv_example.py
- src/api/python/_api.py
Expand test to address github issue
> python: minor test improvement

- .gitlab/build.sh
- .gitlab/test_cpp.sh
- .gitlab/test_python.sh
- README.md
- contrib/Dockerfile
- src/core/nixl_plugin_manager.cpp
- src/plugins/meson.build
- src/plugins/posix/README.md
- src/plugins/posix/meson.build
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_backend.h
- src/plugins/posix/posix_plugin.cpp
- src/utils/common/status.h
- test/nixl/meson.build
- test/nixl/test_plugin.cpp
- test/unit/plugins/meson.build
- test/unit/plugins/posix/meson.build
- test/unit/plugins/posix/nixl_posix_test.cpp
Merged POSIX plugin to local branch to apply CI changes: https://github.com/ai-dynamo/nixl/pull/178
@dfarge I will maintain your authorship in the commit
> POSIX: merge posix plugin to main with CI changes

- src/api/cpp/nixl_types.h
- src/core/nixl_agent.cpp
- src/core/nixl_plugin_manager.cpp
- src/infra/meson.build
- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/utils/ucx/meson.build
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
- test/gtest/meson.build
- test/gtest/ucx_tests.cpp
- Added naive remote failure handling to UCX backend.
- Add gtest `UcxTestFixture`
- Related code refactoring
> UCX backend error handling

- src/plugins/ucx/ucx_backend.cpp
Flush does not imply fencing, so transfer target can end up being notified even before the transfer has completed. This is particularly visible on platforms with weaker ordering (RMA/AM) and with more lanes, as AM might not even be one of the RMA lanes. Perf seen in nixlbench does not seem affected (DRAM and VRAM) by the fix.
> UCX: Only send request notification when requests have completed

- .gitlab/build.sh
- .gitlab/test_cpp.sh
- contrib/Dockerfile
- src/core/meson.build
- src/core/nixl_plugin_manager.cpp
- src/plugins/meson.build
- src/plugins/posix/README.md
- src/plugins/posix/aio_queue.cpp
- src/plugins/posix/aio_queue.h
- src/plugins/posix/async_queue.h
- src/plugins/posix/meson.build
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_backend.h
- src/plugins/posix/posix_plugin.cpp
- src/plugins/posix/queue_factory_impl.h
- src/plugins/posix/uring_queue.cpp
- src/plugins/posix/uring_queue.h
- test/unit/plugins/posix/nixl_posix_test.cpp
Update posix implementation to support both AIO and Uring implementations.
> posix: Updated implementation to support both AIO and Uring

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_backend.h
- src/plugins/ucx_mo/ucx_mo_backend.cpp
- src/plugins/ucx_mo/ucx_mo_backend.h
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
- test/unit/utils/ucx/ucx_am_test.cpp
- test/unit/utils/ucx/ucx_worker_test.cpp
Refactor UCX code to comply with smart pointers resource management according to guidelines.
> UCX: refactor: Apply smart pointer resource management 

- meson.build
- src/core/nixl_agent.cpp
Need to return an error from createBackend.
Cleanup the pluginlist file when rebuilding.
> build: Miscellanous fixes

- src/bindings/rust/Cargo.toml
- src/bindings/rust/README.md
add crate metadata for publishing, required changes for publishing to crates.io
> fix: add crate metadata for publishing

- src/bindings/rust/Cargo.toml
- src/bindings/rust/README.md
> fix: add crate metadata for publishing (#288)

- src/bindings/rust/build.rs
> feat: add ARM (aarch64) build support for nixl-sys (#302)

- meson.build
- src/plugins/posix/meson.build
- src/utils/ucx/ucx_utils.cpp
- test/gtest/ucx_tests.cpp
- test/nixl/meson.build
Taking this change as it enables building the packaged wheels used for release.
> Release 0.2.1 cherry-pick: Fix compilation on RedHat8 (#292)

- benchmark/nixlbench/src/main.cpp
- benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- benchmark/nixlbench/src/worker/nixl/nixl_worker.h
- benchmark/nixlbench/src/worker/worker.cpp
- src/plugins/posix/aio_queue.cpp
Use POSIX plugin with nixlbench. It follows same flow as GDS. 
Also, add another num-files options to create multiple files. Using just 0 file for now.
> nixlbench: Add support for POSIX plugin

- src/plugins/ucx/ucx_plugin.cpp
Small refactor in preparation of next steps.
> Refactor UCX plugin glue.

- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- src/plugins/ucx/ucx_backend.cpp
* Set CUDA device to avoid failure during registration
* Fix NIXLBench stat calculation for single process multi-GPU scenario
> UCX: fix multi GPU scenario (#222)

- src/plugins/ucx/ucx_plugin.cpp
- src/plugins/ucx_mo/meson.build
- src/plugins/ucx_mo/ucx_mo_plugin.cpp
- src/utils/ucx/meson.build
- src/utils/ucx/ucx_utils.h
- test/gtest/error_handling.cpp
+ add ucx_error_handling_mode parameter
+ refactor get_ucx_backend_common_options
+ extend testing with gtest
implemented on top of https://github.com/ai-dynamo/nixl/pull/280/ to address [conversation](https://github.com/ai-dynamo/nixl/pull/280/#discussion_r2095524286)
> BACKEND/UCX_MO: add ucx_error_handling_mode parameter

- .clang-format
Lets start with this version of the file and see if the changes to nixl agent and a ucx header are okay.
> clang: Add clang format file

- benchmark/nixlbench/meson.build
- meson.build
- pyproject.toml
- src/bindings/rust/Cargo.lock
- src/bindings/rust/Cargo.toml
Update versions for 0.3.0 release
> chore: update versions to 0.3.0

- contrib/Dockerfile
- src/bindings/rust/src/lib.rs
Also removed the replicated invalidate methods
> Reordered rust API

- .github/workflows/blossom-ci.yaml
Add initial workflow for running Blossom CI process
> CI: Blossom CI initial commit

- contrib/Dockerfile
- src/bindings/rust/src/lib.rs
* Reordered rust API and removed the replicated invalidate methods.
* Dockerfile: fix meson build
---------
> Reordered rust API (#377)

- benchmark/kvbench/examples/model_llama_3_1_8b.yaml
- benchmark/kvbench/models/deepseek_r1.py
- benchmark/kvbench/models/llama3_1.py
- benchmark/kvbench/models/models.py
* fix naming issues and revert model_config to an optional param in model architectures
* adding optional for model_config
* fix ci issues
> fix: consistent naming for NIXL KV Bench  - 0.3.0

- src/bindings/rust/src/lib.rs
https://github.com/ai-dynamo/nixl/pull/400
> SRC/BINDINGS/RUST: Revert has_overlaps to pub

- src/api/cpp/backend/backend_aux.h
- src/api/cpp/nixl_types.h
Replaced classes with only public members with structures.
> API/CPP: Replaced classes with only public members with structures.

- CODEOWNERS
Added myself as a codeowner of the bindings folder.
To get notified about new changes there.
> CODEOWNERS: added roiedanino as codeowner of Rust bindings

- contrib/Dockerfile
- contrib/Dockerfile.manylinux
- test/unit/plugins/cuda_gds/meson.build
Address dependencies in test.
Fixes to Dockerfile for CI.
> fix: GDS deps and Dockerfile updates

- contrib/aws-efa/aws_test.sh
Reduces log verbosity in AWS EFA test script waiting loops by replacing verbose status messages with progress dots.
The waiting loops generate excessive log output due to bash `-x` and per-iteration status messages, making CI logs difficult to read.
- Disables bash execution tracing (`set +x`) within `wait_for_status` function during polling
- Replaces detailed status messages with simple dot progress indicators
- Uses `echo -e` for cleaner final status messages
- Restores tracing after function exits
> CI: Reduce log verbosity in AWS EFA test waiting loops

- contrib/build-container.sh
* add wheel-base to pass the the wheel building platform.
* Update build-container.sh
> build: Add wheel-base to pass the the wheel building platform. (#468)

- test/gtest/test_transfer.cpp
Fixed gtest output.
Before
```
[     INFO ] Thread 3: 40x1000x1=40000 bytes in [     INFO ] Thread 0: 40x1000x1=40000 bytes in 0.002957810.00295864 seconds ( seconds (0.0125948 GB/s)0.0125912 GB/s)
[     INFO ] Thread 1: 40x1000x1=40000 bytes in 0.00573828 seconds (0.006492 GB/s)
[     INFO ] Thread 2: 40x1000x1=40000 bytes in 0.00586466 seconds (0.0063521 GB/s)
```
After
```
[     INFO ] Thread 3: 40x1000x1=40000 bytes in 0.00131894 seconds (0.0282445 GB/s)
[     INFO ] Thread 1: 40x1000x1=40000 bytes in 0.00241372 seconds (0.0154338 GB/s)
[     INFO ] Thread 0: 40x1000x1=40000 bytes in 0.0037073 seconds (0.0100485 GB/s)
[     INFO ] Thread 2: 40x1000x1=40000 bytes in 0.00377053 seconds (0.00988002 GB/s)
```
> TEST/GTEST: Added mutex before logging.

- src/plugins/ucx/ucx_backend.cpp
- src/utils/ucx/ucx_utils.cpp
- src/utils/ucx/ucx_utils.h
- test/unit/utils/ucx/ucx_worker_test.cpp
Add check that UCX correctly recognizes GPU memory
Better debugging experience when UCX is compiled without CUDA support or fails to find some CUDA libs
> UCX: Check if UCX recognizes GPU mem correctly

- src/plugins/posix/aio_queue.cpp
- src/plugins/posix/aio_queue.h
- src/plugins/posix/posix_backend.cpp
- src/plugins/posix/posix_queue.h
- src/plugins/posix/uring_queue.cpp
- src/plugins/posix/uring_queue.h
- test/unit/plugins/posix/nixl_posix_test.cpp
_Fixes bugs on re-posting requests and adds related test case_
_Reset the counter for num of completed transfers within the posix request handle and moved some necessary work from UringQueue::prepIO to UringQueue::submit, that wouldn't otherwise happen on reposting to the same handle._
> POSIX: Fixed bugs on re-posting requests and added related test case

- .ci/jenkins/pipeline/proj-jjb.yaml
- benchmark/nixlbench/meson.build
- examples/rust/Cargo.lock
- meson.build
- pyproject.toml
- src/bindings/rust/Cargo.lock
- src/bindings/rust/Cargo.toml
Update release version for 0.4.0
> chore: Update release version for 0.4.0

- benchmark/nixlbench/contrib/Dockerfile
Installs UCX to default location to make sure it is the one which is used
Fixes [internal bug link](https://nvbugspro.nvidia.com/bug/5376967)
> BENCH: Fix UCX install path in dockerfile

- benchmark/nixlbench/contrib/Dockerfile
Installs UCX to default location to make sure it is the one which is used
Fixes [internal bug link](https://nvbugspro.nvidia.com/bug/5376967)
Cherry-picked https://github.com/ai-dynamo/nixl/pull/533
> BENCH: Fix UCX install path in dockerfile - 0.4.0

- test/unit/plugins/posix/nixl_posix_test.cpp
> POSIX: Fix repost test logic error

- benchmark/kvbench/pyproject.toml
Remove aspostorage dependency in kvbench
> build: Remove aspostorage dependency in kvbench - 0.4.0

- src/plugins/ucx/ucx_backend.cpp
- src/plugins/ucx/ucx_plugin.cpp
- src/utils/ucx/ucx_utils.cpp
Refactoring of `nixlUcxEngine::nixlUcxEngine`
~~NOTE: in dependency from https://github.com/ai-dynamo/nixl/pull/499~~
to resolve [this](https://github.com/ai-dynamo/nixl/pull/499/files#r2183166510) conversation
del usage of `initErr` and replaced with exceptions
> UCX/BACKEND: refactor nixlUcxEngine::nixlUcxEngine

- src/plugins/obj/obj_backend.cpp
- src/plugins/obj/obj_backend.h
- src/plugins/obj/obj_executor.h
- src/plugins/obj/obj_s3_client.cpp
- src/plugins/obj/obj_s3_client.h
- test/gtest/unit/agent/agent.cpp
- test/gtest/unit/main.cpp
- test/gtest/unit/obj/obj.cpp
Verify compliance with clang-tidy.
> Fix Obj plugin and tests according to project code style

- ATTRIBUTIONS-CPP.md
Update attributions.md file for the release 0.5.0. 
The `cpprestsdk` dependency has been removed in the new version 0.5.0.
> chore: Update ATTRIBUTIONS-CPP.md

- .ci/jenkins/pipeline/proj-jjb.yaml
- Cargo.lock
- Cargo.toml
- benchmark/nixlbench/meson.build
- examples/rust/Cargo.lock
- meson.build
- pyproject.toml
Update release version for NIXL 0.5.1
> chore: Update release version for NIXL

- src/api/python/_api.py
Added pythonic objects for xfer and dlist handles
For some of the current use cases, users create the xfer_req and check for it until it's done, call the release, and then remove it from a list. To make it more pythonic, made the xfer_req to be a python object that has del method, so when removed from the list, would automatically be called. Also helps with type checking in compile time.
Added two wrapper classes for the handles, and some optimizations to make the post and check times minimal on critical path. Also added some protection code for when a handle cannot be released (the transfer is not complete), both in the delete method of the handle, and then delete of the agent to retry to release those elements.
> Added pythonic objects for xfer and dlist handles

- benchmark/nixlbench/src/utils/utils.cpp
- benchmark/nixlbench/src/utils/utils.h
- benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
- src/plugins/hf3fs/hf3fs_backend.cpp
- src/plugins/hf3fs/hf3fs_backend.h
- test/unit/plugins/hf3fs/nixl_hf3fs_mt_test.cpp
Use mempool in HF3FS plugin
Avoid allocating memory in datapath
> [HF3FS] add mempool

- benchmark/kvbench/README.md
- benchmark/kvbench/commands/args.py
- benchmark/kvbench/commands/nixlbench.py
- benchmark/kvbench/main.py
Update kvbench parameters to line with nixlbench. Add remaining plugins to kvbench. Update nixlbench parameters in kvbench. Some minor edits to kvbench args order.
To make sure both benchmarks are consistent in evaluation of NIXL and NIXL Plugins.
> benchmark/kvbench: Update to make consistent with nixlbench

- CODEOWNERS
Add @ovidiusm as owner for python bindings
> Codeowners: create entry for python

- CODEOWNERS
> CODEWONERS: Fix syntax

- src/core/nixl_agent.cpp
- src/utils/common/nixl_log.h
- src/utils/serdes/meson.build
- src/utils/serdes/serdes.cpp
Removed the macros in nixl_agent.
Better to avoid such macros in general.
> Removed the macros in nixl_agent.

- src/utils/libfabric/libfabric_rail.cpp
- src/utils/libfabric/libfabric_rail.h
Currently the EFA provider does manual progress so the retry operation fails.
So when we need to ensure that to progress the completion queue manually before retrying.
> Progress the completion queue manually in case of Resource Unavailable

- src/utils/libfabric/libfabric_topology.cpp
Cherry-pick of #860
---
Root cause:
- When hwloc_topology_load() failed, it left hwloc_topology in a partially initialized state
- The constructor would throw an exception, triggering the destructor
- The destructor would attempt to destroy the same partially initialized topology, causing a double-free segmentation fault
Changes:
- Add proper null pointer initialization and verification throughout the function
- Implement safe cleanup in error paths to prevent double-free conditions
- Add multiple safety checks before and after hwloc operations
- Ensure hwloc_topology_destroy() is only called on valid topology objects
_Describe what this PR is doing._
_Justification for the PR. If there is an existing issue/bug, please reference it. For
bug fixes, the 'Why?' and 'What?' can be merged into …
> fix(libfabric): prevent double-free segfault in hwloc topology initialization
